#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('Atta', '@package_version@');

$application->addCommands(
    [
        new Atta\Console\PostgresWorkerConsole(),
        new Atta\Console\MysqlWorkerConsole(),
        new Atta\Console\MongoWorkerConsole(),
        new Atta\Console\BackupComposerConsole(),
        new Atta\Console\PublisherConsole(),
        new Atta\Console\UpdateConsole(),
    ]
);

$application->run();
