#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('Atta', '0.1.0');

$application->addCommands(
    [
        new Atta\Console\PostgresWorkerConsole(),
        new Atta\Console\MysqlWorkerConsole(),
        new Atta\Console\MongoWorkerConsole(),
        new Atta\Console\BackupComposerConsole(),
    ]
);

$application->run();
